// Code generated by metamodel. DO NOT EDIT.
// Author: namnv2496

package repository

// Feature_ contains field name constants for Feature
var Feature_ = struct {
	TableName   string
	FeatureName Field
	ScenarioID  Field
	Description Field
}{
	TableName:   "features",
	FeatureName: Field{FieldName: "feature_name", TableName: "features"},
	ScenarioID:  Field{FieldName: "scenario_id", TableName: "features"},
	Description: Field{FieldName: "description", TableName: "features"},
}
